### ISSUE TITLE
Potentially port to the Griddly RL Engine

### ISSUE THREAD

**Issue by Bam4d** [danijar/crafter#7]
Hi @danijar! 

I'm the creator of Griddly https://griddly.readthedocs.io/en/latest/ and I'm pretty sure it would be possible to port most of the crafter environment to use the Griddly Engine.

Using Griddly you get a bunch of features that work *out of the box*
* Multi-agent interfaces (just put more players in the level map and it *just works*)
   * Hardware accellerated video recording per-agent and globally.
* Really easily modifiable mechanics (you just change the YAML a bit)
* 5 different ways to produce observations, 
    * Vector observations can be about 70k observations per second (on a single thread))
    * 3 different GPU accellerated observation types (probably around 4k obs per second (on a single thread))
    * ASCII observations (if you're one of those NetHack/Dwarf Fortress nerds)
* RLLib support (if you want to do multiple policies/agents competitive/collaborative etc)

It would be super simple to skin crafter like this also for interesting demos: 
![image](https://user-images.githubusercontent.com/1370765/134706536-cb951517-3370-4a00-b4f6-78a52762eff9.png)

What do you think? There's definitely some things I'd have to add to Griddly (such as the chasing mechanics) But I've been looking to do that for a while anyway.

Ill see if I can make a super simple example and add some images/gifs this weekend.

**Comment by danijar** [comment]
Hi, your engine looks cool. Crafter is already implemented, so I don't see much of a benefit of switching to a game engine. Crafter is intentionally written entirely in Python to make it easy to modify for research purposes.

I know that rendering in C/C++ could make it faster, but that would only be relevant if somebody wanted to train on a huge amount of experience. To me, the large-data regime is less interesting for this particular environment, because we pretty much know that we can solve RL problems like this one given unlimited experience and compute.

**Comment by Bam4d** [comment]
Awesome. I might get it working with Griddly for my own side-project, the multi-agent potential is an interesting angle that I think researchers will be interested in also.

I might ping an update here once i get that side of stuff working.

**Comment by danijar** [comment]
Sounds good! Yes, multi agent support would be cool.
